version: "3.8"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=food;User Id=sa;Password=123456;TrustServerCertificate=True
