version: "3.8"
services:
  app:
    build: .
    ports:
      - "5122:5122"
    environment:
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=Microservice_BookingDB;User Id=sa;Password=khoa31102003;TrustServerCertificate=True

