version: "3.8"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=Microservice_CommunicateDB;User Id=sa;Password=khoa31102003;TrustServerCertificate=True

