services:
  userservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5157:5157"
    environment:
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=Microservice_UserDB;User Id=sa;Password=0789616573;TrustServerCertificate=True

