version: "3.8"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=DESKTOP-CTS44AC\\MAIN;User Id=sa;Password=0789616573;TrustServerCertificate=True


